packageExtensions:
  "@storybook/addons@^5.3.19":
    dependencies:
      regenerator-runtime: '*'
  "@storybook/api@^5.3.19":
    dependencies:
      react-dom: "^16.0.0"
  "@storybook/addon-actions@^5.3.19":
    dependencies:
      regenerator-runtime: '*'
      react-dom: "^16.0.0"
  "@storybook/addon-knobs@^5.3.19":
    dependencies:
      regenerator-runtime: '*'
      react-dom: "^16.0.0"
  "@dump247/storybook-state@^1.6.1":
    dependencies:
      react-dom: "^16.0.0"
  "create-react-class@^15.6.3":
    dependencies:
      react: "^16.0.0"
  jss-keyframes@^0.1.0:
    dependencies:
      jss: ^10.0.0
  ramda-adjunct@^2.27.0:
    dependencies:
      ramda: ^0.27.0
  rc-trigger@^4.3.4:
    dependencies:
      react: "^16.0.0"
  react-color@^2.18.1:
    dependencies:
      react: "^16.0.0"
  react-d3-core@^1.3.9:
    dependencies:
      react: "^16.0.0"
      react-dom: "^16.0.0"
  react-d3-shape@^0.3.25:
    dependencies:
      react: "^16.0.0"
      react-dom: "^16.0.0"
  react-notifications@^1.6.0:
    dependencies:
      react: "^16.0.0"
      react-dom: "^16.0.0"
  react-sortable-tree@^2.7.1:
    dependencies:
      react-dnd: ^11.1.3
  react-swipeable-views-utils@^0.13.9:
    dependencies:
      react: "^16.0.0"
  snowpack@^2.0.0:
    dependencies:
      "@babel/core": ^7.0.0
      "@snowpack/app-scripts-react": ^1.4.0

yarnPath: ".yarn/releases/yarn-berry.js"
