packageExtensions:
  "@dump247/storybook-state@*":
    dependencies:
      react-dom: ^16.0.0
  "@storybook/addon-actions@*":
    dependencies:
      react-dom: ^16.0.0
      regenerator-runtime: "*"
  "@storybook/addon-knobs@*":
    dependencies:
      react-dom: ^16.0.0
      regenerator-runtime: "*"
  "@storybook/addons@*":
    dependencies:
      regenerator-runtime: "*"
  "@storybook/api@*":
    dependencies:
      react-dom: ^16.0.0
  create-react-class@*:
    dependencies:
      react: ^16.0.0
  jss-keyframes@*:
    dependencies:
      jss: ^10.0.0
  ramda-adjunct@*:
    dependencies:
      ramda: ^0.27.0
  rc-collapse@*:
    dependencies:
      react: ^16.0.0
  rc-slider@*:
    dependencies:
      react: ^16.0.0
  rc-trigger@*:
    dependencies:
      react: ^16.0.0
  react-color@*:
    dependencies:
      react: ^16.0.0
  react-d3-core@*:
    dependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  react-d3-shape@*:
    dependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  react-notifications@*:
    dependencies:
      react: ^16.0.0
      react-dom: ^16.0.0
  react-sortable-tree@*:
    dependencies:
      react-dnd: ^11.1.3
  react-swipeable-views-utils@*:
    dependencies:
      react: ^16.0.0
  snowpack@*:
    dependencies:
      "@babel/core": ^7.0.0
      "@snowpack/app-scripts-react": ^1.4.0
  react-base16-styling@*:
    dependencies:
      "babel-runtime": '*'
  component-classes@*:
    dependencies:
      indexof: '*'

yarnPath: .yarn/releases/yarn-sources.cjs
